### PR TITLE
[STAN-886] Add google site code meta tag

### PR DESCRIPTION
**Pull request by roc**
- In order to confirm we own each domain to google, we can attach these site codes
- Site codes to be added per environment in github

Capture d’écran 2022-09-02 à 15 41 32

### CODE REVIEW

**Review by easternbloc — APPROVED** [review]

**Comment by lennym** [comment]
Out of curiosity, why do "we" need confirm we own the site? And who is "we" in this arrangement?

**Comment by roc** [comment]
> Out of curiosity, why do "we" need confirm we own the site? And who is "we" in this arrangement?

It's for google site verification, https://support.google.com/webmasters/answer/9008080?hl=en

From their blurb in the docs:

> What is ownership verification?
Ownership verification means proving to Search Console that you own a specific website. Site owners in Search Console have access to sensitive Google Search data for a site, and can affect a site's presence and behavior on Google Search and other Google services. A verified owner can grant [access](https://support.google.com/webmasters/answer/7687615) to other people to see or manage site data in Search Console.

I think Bhurut is planning to tweak some search console settings when we've verified the domains

**Comment by lennym** [comment]
Thanks! I assume the value of the token was provided by Bhurut then?

**Comment by roc** [comment]
Yeah that's right. I think after verification we can probably remove the tag

**Pull request merged**
